spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-uno
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mariadb://localhost:3308/payments_db
    username: user
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Database Naming strategy
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#sensitive details retracted.
mpesa:
  daraja:
    consumerKey: consumer_key
    consumerSecret: consumer_secret
    grantType: client_credentials
    oauthEndpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
    b2cRequestEndpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v3/paymentrequest
    shortCode: business_short_code
    queueTimeOutURL: https://mydomain.com/b2c/queue
    resultURL: https://mydomain.com/b2c/result
    responseType: Completed

